# adb shell pm uninstall --user 0 com.google.android.captiveportallogin
# adb shell pm uninstall --user 0 com.google.android.ext.services
# adb shell pm uninstall --user 0 com.google.android.modulemetadata
# adb shell pm uninstall --user 0 com.google.android.networkstack
# adb shell pm uninstall --user 0 com.google.android.packageinstaller
# adb shell pm uninstall --user 0 com.google.android.permissioncontroller
# adb shell pm uninstall --user 0 com.google.mainline.adservices
# adb shell pm uninstall --user 0 com.google.mainline.telemetry
adb shell pm uninstall --user 0 androidx.compose.material.catalog
adb shell pm uninstall --user 0 com.android.chrome
adb shell pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
adb shell pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
adb shell pm uninstall --user 0 com.android.vending
adb shell pm uninstall --user 0 com.chrome.beta
adb shell pm uninstall --user 0 com.chrome.canary
adb shell pm uninstall --user 0 com.chrome.dev
adb shell pm uninstall --user 0 com.google.android.accessibility.reader
adb shell pm uninstall --user 0 com.google.android.accessibility.soundamplifier
adb shell pm uninstall --user 0 com.google.android.accessibility.switchaccess
adb shell pm uninstall --user 0 com.google.android.adservices.api
adb shell pm uninstall --user 0 com.google.android.apps.accessibility.auditor
adb shell pm uninstall --user 0 com.google.android.apps.accessibility.magnifier
adb shell pm uninstall --user 0 com.google.android.apps.accessibility.maui.actionblocks
adb shell pm uninstall --user 0 com.google.android.apps.accessibility.reveal
adb shell pm uninstall --user 0 com.google.android.apps.accessibility.voiceaccess
adb shell pm uninstall --user 0 com.google.android.apps.actionsservice
adb shell pm uninstall --user 0 com.google.android.apps.adm
adb shell pm uninstall --user 0 com.google.android.apps.ads.homeservices
adb shell pm uninstall --user 0 com.google.android.apps.adwords
adb shell pm uninstall --user 0 com.google.android.apps.aiy
adb shell pm uninstall --user 0 com.google.android.apps.assistant
adb shell pm uninstall --user 0 com.google.android.apps.audition
adb shell pm uninstall --user 0 com.google.android.apps.authenticator2
adb shell pm uninstall --user 0 com.google.android.apps.automotive.gamesnacks
adb shell pm uninstall --user 0 com.google.android.apps.automotive.inputmethod
adb shell pm uninstall --user 0 com.google.android.apps.automotive.templates.host
adb shell pm uninstall --user 0 com.google.android.apps.baselinestudy
adb shell pm uninstall --user 0 com.google.android.apps.blogger
adb shell pm uninstall --user 0 com.google.android.apps.books
adb shell pm uninstall --user 0 com.google.android.apps.camera.poseidon
adb shell pm uninstall --user 0 com.google.android.apps.camera.services
adb shell pm uninstall --user 0 com.google.android.apps.carrier.carrierwifi
adb shell pm uninstall --user 0 com.google.android.apps.chromecast.app
adb shell pm uninstall --user 0 com.google.android.apps.classroom
adb shell pm uninstall --user 0 com.google.android.apps.cloud.cloudbi
adb shell pm uninstall --user 0 com.google.android.apps.cloudconsole
adb shell pm uninstall --user 0 com.google.android.apps.cultural
adb shell pm uninstall --user 0 com.google.android.apps.docs
adb shell pm uninstall --user 0 com.google.android.apps.docs.editors.docs
adb shell pm uninstall --user 0 com.google.android.apps.docs.editors.sheets
adb shell pm uninstall --user 0 com.google.android.apps.docs.editors.slides
adb shell pm uninstall --user 0 com.google.android.apps.dynamite
adb shell pm uninstall --user 0 com.google.android.apps.enterprise.cpanel
adb shell pm uninstall --user 0 com.google.android.apps.fitness
adb shell pm uninstall --user 0 com.google.android.apps.giant
adb shell pm uninstall --user 0 com.google.android.apps.googleassistant
adb shell pm uninstall --user 0 com.google.android.apps.googlevoice
adb shell pm uninstall --user 0 com.google.android.apps.health.research.studies
adb shell pm uninstall --user 0 com.google.android.apps.healthdata
adb shell pm uninstall --user 0 com.google.android.apps.helprtc
adb shell pm uninstall --user 0 com.google.android.apps.jam
adb shell pm uninstall --user 0 com.google.android.apps.kids.familylink
adb shell pm uninstall --user 0 com.google.android.apps.kids.familylinkhelper
adb shell pm uninstall --user 0 com.google.android.apps.magazines
adb shell pm uninstall --user 0 com.google.android.apps.maps
adb shell pm uninstall --user 0 com.google.android.apps.mapslite
adb shell pm uninstall --user 0 com.google.android.apps.mediashell
adb shell pm uninstall --user 0 com.google.android.apps.meetings
adb shell pm uninstall --user 0 com.google.android.apps.messaging
adb shell pm uninstall --user 0 com.google.android.apps.motionsense.bridge
adb shell pm uninstall --user 0 com.google.android.apps.navlite
adb shell pm uninstall --user 0 com.google.android.apps.nbu.files
adb shell pm uninstall --user 0 com.google.android.apps.nbu.paisa.user
adb shell pm uninstall --user 0 com.google.android.apps.onlineinsightspanel
adb shell pm uninstall --user 0 com.google.android.apps.paidtasks
adb shell pm uninstall --user 0 com.google.android.apps.pdfviewer
adb shell pm uninstall --user 0 com.google.android.apps.photos
adb shell pm uninstall --user 0 com.google.android.apps.photos.scanner
adb shell pm uninstall --user 0 com.google.android.apps.photosgo
adb shell pm uninstall --user 0 com.google.android.apps.pixel.health
adb shell pm uninstall --user 0 com.google.android.apps.pixelmigrate
adb shell pm uninstall --user 0 com.google.android.apps.playconsole
adb shell pm uninstall --user 0 com.google.android.apps.podcasts
adb shell pm uninstall --user 0 com.google.android.apps.recorder
adb shell pm uninstall --user 0 com.google.android.apps.restore
adb shell pm uninstall --user 0 com.google.android.apps.safetyhub
adb shell pm uninstall --user 0 com.google.android.apps.searchlite
adb shell pm uninstall --user 0 com.google.android.apps.security.securityhub
adb shell pm uninstall --user 0 com.google.android.apps.seekh
adb shell pm uninstall --user 0 com.google.android.apps.subscriptions.red
adb shell pm uninstall --user 0 com.google.android.apps.tachyon
adb shell pm uninstall --user 0 com.google.android.apps.tasks
adb shell pm uninstall --user 0 com.google.android.apps.translate
adb shell pm uninstall --user 0 com.google.android.apps.turbo
adb shell pm uninstall --user 0 com.google.android.apps.tycho
adb shell pm uninstall --user 0 com.google.android.apps.userpanel
adb shell pm uninstall --user 0 com.google.android.apps.village.boond
adb shell pm uninstall --user 0 com.google.android.apps.walletnfcrel
adb shell pm uninstall --user 0 com.google.android.apps.wallpaper
adb shell pm uninstall --user 0 com.google.android.apps.wear.companion
adb shell pm uninstall --user 0 com.google.android.apps.wearables.maestro.companion
adb shell pm uninstall --user 0 com.google.android.apps.wellbeing
adb shell pm uninstall --user 0 com.google.android.apps.wifisetup.app
adb shell pm uninstall --user 0 com.google.android.apps.work.clouddpc
adb shell pm uninstall --user 0 com.google.android.apps.youtube.creator
adb shell pm uninstall --user 0 com.google.android.apps.youtube.kids
adb shell pm uninstall --user 0 com.google.android.apps.youtube.music
adb shell pm uninstall --user 0 com.google.android.apps.youtube.music.pwa
adb shell pm uninstall --user 0 com.google.android.apps.youtube.producer
adb shell pm uninstall --user 0 com.google.android.apps.youtube.unplugged
adb shell pm uninstall --user 0 com.google.android.as
adb shell pm uninstall --user 0 com.google.android.as.oss
adb shell pm uninstall --user 0 com.google.android.backdrop
adb shell pm uninstall --user 0 com.google.android.backuptransport
adb shell pm uninstall --user 0 com.google.android.calculator
adb shell pm uninstall --user 0 com.google.android.calendar
adb shell pm uninstall --user 0 com.google.android.cellbroadcastreceiver
adb shell pm uninstall --user 0 com.google.android.cellbroadcastservice
adb shell pm uninstall --user 0 com.google.android.configupdater
adb shell pm uninstall --user 0 com.google.android.connectivity.resources
adb shell pm uninstall --user 0 com.google.android.contacts
adb shell pm uninstall --user 0 com.google.android.deskclock
adb shell pm uninstall --user 0 com.google.android.dialer
adb shell pm uninstall --user 0 com.google.android.documentsui
adb shell pm uninstall --user 0 com.google.android.embedded.projection
adb shell pm uninstall --user 0 com.google.android.euicc
adb shell pm uninstall --user 0 com.google.android.ext.shared
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.google.android.gm
adb shell pm uninstall --user 0 com.google.android.gm.lite
adb shell pm uninstall --user 0 com.google.android.gms
adb shell pm uninstall --user 0 com.google.android.gms.location.history
adb shell pm uninstall --user 0 com.google.android.gms.supervision
adb shell pm uninstall --user 0 com.google.android.GoogleCamera
adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall --user 0 com.google.android.gsf
adb shell pm uninstall --user 0 com.google.android.gsf.login
adb shell pm uninstall --user 0 com.google.android.ims
adb shell pm uninstall --user 0 com.google.android.inputmethod.latin
adb shell pm uninstall --user 0 com.google.android.instantapps.supervisor
adb shell pm uninstall --user 0 com.google.android.katniss
adb shell pm uninstall --user 0 com.google.android.keep
adb shell pm uninstall --user 0 com.google.android.leanbacklauncher
adb shell pm uninstall --user 0 com.google.android.marvin.talkback
adb shell pm uninstall --user 0 com.google.android.music
adb shell pm uninstall --user 0 com.google.android.nearby.halfsheet
adb shell pm uninstall --user 0 com.google.android.networkstack.tethering
adb shell pm uninstall --user 0 com.google.android.networkstack.tethering.overlay
adb shell pm uninstall --user 0 com.google.android.ondevicepersonalization.services
adb shell pm uninstall --user 0 com.google.android.onetimeinitializer
adb shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.asi
adb shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.common
adb shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.geotz
adb shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.gsa
adb shell pm uninstall --user 0 com.google.android.overlay.gmsconfig.photos
adb shell pm uninstall --user 0 com.google.android.overlay.modules.captiveportallogin.forframework
adb shell pm uninstall --user 0 com.google.android.overlay.modules.cellbroadcastreceiver
adb shell pm uninstall --user 0 com.google.android.overlay.modules.cellbroadcastservice
adb shell pm uninstall --user 0 com.google.android.overlay.modules.documentsui
adb shell pm uninstall --user 0 com.google.android.overlay.modules.ext.services
adb shell pm uninstall --user 0 com.google.android.overlay.modules.modulemetadata.forframework
adb shell pm uninstall --user 0 com.google.android.overlay.modules.permissioncontroller
adb shell pm uninstall --user 0 com.google.android.overlay.modules.permissioncontroller.forframework
adb shell pm uninstall --user 0 com.google.android.partnersetup
adb shell pm uninstall --user 0 com.google.android.play.games
adb shell pm uninstall --user 0 com.google.android.printservice.recommendation
adb shell pm uninstall --user 0 com.google.android.projection.gearhead
adb shell pm uninstall --user 0 com.google.android.providers.media.module
adb shell pm uninstall --user 0 com.google.android.safetycenter.resources
adb shell pm uninstall --user 0 com.google.android.sdksandbox
adb shell pm uninstall --user 0 com.google.android.setupwizard
adb shell pm uninstall --user 0 com.google.android.syncadapters.calendar
adb shell pm uninstall --user 0 com.google.android.syncadapters.contacts
adb shell pm uninstall --user 0 com.google.android.tts
adb shell pm uninstall --user 0 com.google.android.tungsten.setupwraith
adb shell pm uninstall --user 0 com.google.android.tv
adb shell pm uninstall --user 0 com.google.android.tv.remote.service
adb shell pm uninstall --user 0 com.google.android.tvlauncher
adb shell pm uninstall --user 0 com.google.android.tvrecommendations
adb shell pm uninstall --user 0 com.google.android.videos
adb shell pm uninstall --user 0 com.google.android.wearable.app
adb shell pm uninstall --user 0 com.google.android.wearable.assistant
adb shell pm uninstall --user 0 com.google.android.wearable.fitbit.mcu.data
adb shell pm uninstall --user 0 com.google.android.wearable.healthservices
adb shell pm uninstall --user 0 com.google.android.wearable.pixel.pdms
adb shell pm uninstall --user 0 com.google.android.wearable.protolayout.renderer
adb shell pm uninstall --user 0 com.google.android.wearable.sysui
adb shell pm uninstall --user 0 com.google.android.wearable.watchface.rwf
adb shell pm uninstall --user 0 com.google.android.wearable.weather
adb shell pm uninstall --user 0 com.google.android.webview
adb shell pm uninstall --user 0 com.google.android.webview.beta
adb shell pm uninstall --user 0 com.google.android.webview.canary
adb shell pm uninstall --user 0 com.google.android.webview.dev
adb shell pm uninstall --user 0 com.google.android.youtube
adb shell pm uninstall --user 0 com.google.android.youtube.tv
adb shell pm uninstall --user 0 com.google.android.youtube.tvkids
adb shell pm uninstall --user 0 com.google.android.youtube.tvmusic
adb shell pm uninstall --user 0 com.google.android.youtube.tvunplugged
adb shell pm uninstall --user 0 com.google.ar.core
adb shell pm uninstall --user 0 com.google.ar.lens
adb shell pm uninstall --user 0 com.google.audio.hearing.visualization.accessibility.scribe
adb shell pm uninstall --user 0 com.google.chromeremotedesktop
adb shell pm uninstall --user 0 com.google.earth
adb shell pm uninstall --user 0 com.google.enterprise.topaz.mobile.android
adb shell pm uninstall --user 0 com.google.location.nearby.apps.fastpair.validator
adb shell pm uninstall --user 0 com.google.research.projectrelate
adb shell pm uninstall --user 0 com.google.samples.apps.cardboarddemo
adb shell pm uninstall --user 0 com.google.samples.apps.iosched
adb shell pm uninstall --user 0 com.google.socratic
adb shell pm uninstall --user 0 com.google.toontastic
adb shell pm uninstall --user 0 com.niksoftware.snapseed
