# adb shell cmd package install-existing com.google.android.captiveportallogin
# adb shell cmd package install-existing com.google.android.ext.services
# adb shell cmd package install-existing com.google.android.modulemetadata
# adb shell cmd package install-existing com.google.android.networkstack
# adb shell cmd package install-existing com.google.android.packageinstaller
# adb shell cmd package install-existing com.google.android.permissioncontroller
# adb shell cmd package install-existing com.google.mainline.adservices
# adb shell cmd package install-existing com.google.mainline.telemetry
adb shell cmd package install-existing androidx.compose.material.catalog
adb shell cmd package install-existing com.android.chrome
adb shell cmd package install-existing com.android.hotwordenrollment.okgoogle
adb shell cmd package install-existing com.android.hotwordenrollment.xgoogle
adb shell cmd package install-existing com.android.vending
adb shell cmd package install-existing com.chrome.beta
adb shell cmd package install-existing com.chrome.canary
adb shell cmd package install-existing com.chrome.dev
adb shell cmd package install-existing com.google.android.accessibility.reader
adb shell cmd package install-existing com.google.android.accessibility.soundamplifier
adb shell cmd package install-existing com.google.android.accessibility.switchaccess
adb shell cmd package install-existing com.google.android.adservices.api
adb shell cmd package install-existing com.google.android.apps.accessibility.auditor
adb shell cmd package install-existing com.google.android.apps.accessibility.magnifier
adb shell cmd package install-existing com.google.android.apps.accessibility.maui.actionblocks
adb shell cmd package install-existing com.google.android.apps.accessibility.reveal
adb shell cmd package install-existing com.google.android.apps.accessibility.voiceaccess
adb shell cmd package install-existing com.google.android.apps.actionsservice
adb shell cmd package install-existing com.google.android.apps.adm
adb shell cmd package install-existing com.google.android.apps.ads.homeservices
adb shell cmd package install-existing com.google.android.apps.adwords
adb shell cmd package install-existing com.google.android.apps.aiy
adb shell cmd package install-existing com.google.android.apps.assistant
adb shell cmd package install-existing com.google.android.apps.audition
adb shell cmd package install-existing com.google.android.apps.authenticator2
adb shell cmd package install-existing com.google.android.apps.automotive.gamesnacks
adb shell cmd package install-existing com.google.android.apps.automotive.inputmethod
adb shell cmd package install-existing com.google.android.apps.automotive.templates.host
adb shell cmd package install-existing com.google.android.apps.baselinestudy
adb shell cmd package install-existing com.google.android.apps.blogger
adb shell cmd package install-existing com.google.android.apps.books
adb shell cmd package install-existing com.google.android.apps.camera.poseidon
adb shell cmd package install-existing com.google.android.apps.camera.services
adb shell cmd package install-existing com.google.android.apps.carrier.carrierwifi
adb shell cmd package install-existing com.google.android.apps.chromecast.app
adb shell cmd package install-existing com.google.android.apps.classroom
adb shell cmd package install-existing com.google.android.apps.cloud.cloudbi
adb shell cmd package install-existing com.google.android.apps.cloudconsole
adb shell cmd package install-existing com.google.android.apps.cultural
adb shell cmd package install-existing com.google.android.apps.docs
adb shell cmd package install-existing com.google.android.apps.docs.editors.docs
adb shell cmd package install-existing com.google.android.apps.docs.editors.sheets
adb shell cmd package install-existing com.google.android.apps.docs.editors.slides
adb shell cmd package install-existing com.google.android.apps.dynamite
adb shell cmd package install-existing com.google.android.apps.enterprise.cpanel
adb shell cmd package install-existing com.google.android.apps.fitness
adb shell cmd package install-existing com.google.android.apps.giant
adb shell cmd package install-existing com.google.android.apps.googleassistant
adb shell cmd package install-existing com.google.android.apps.googlevoice
adb shell cmd package install-existing com.google.android.apps.health.research.studies
adb shell cmd package install-existing com.google.android.apps.healthdata
adb shell cmd package install-existing com.google.android.apps.helprtc
adb shell cmd package install-existing com.google.android.apps.jam
adb shell cmd package install-existing com.google.android.apps.kids.familylink
adb shell cmd package install-existing com.google.android.apps.kids.familylinkhelper
adb shell cmd package install-existing com.google.android.apps.magazines
adb shell cmd package install-existing com.google.android.apps.maps
adb shell cmd package install-existing com.google.android.apps.mapslite
adb shell cmd package install-existing com.google.android.apps.mediashell
adb shell cmd package install-existing com.google.android.apps.meetings
adb shell cmd package install-existing com.google.android.apps.messaging
adb shell cmd package install-existing com.google.android.apps.motionsense.bridge
adb shell cmd package install-existing com.google.android.apps.navlite
adb shell cmd package install-existing com.google.android.apps.nbu.files
adb shell cmd package install-existing com.google.android.apps.nbu.paisa.user
adb shell cmd package install-existing com.google.android.apps.onlineinsightspanel
adb shell cmd package install-existing com.google.android.apps.paidtasks
adb shell cmd package install-existing com.google.android.apps.pdfviewer
adb shell cmd package install-existing com.google.android.apps.photos
adb shell cmd package install-existing com.google.android.apps.photos.scanner
adb shell cmd package install-existing com.google.android.apps.photosgo
adb shell cmd package install-existing com.google.android.apps.pixel.health
adb shell cmd package install-existing com.google.android.apps.pixelmigrate
adb shell cmd package install-existing com.google.android.apps.playconsole
adb shell cmd package install-existing com.google.android.apps.podcasts
adb shell cmd package install-existing com.google.android.apps.recorder
adb shell cmd package install-existing com.google.android.apps.restore
adb shell cmd package install-existing com.google.android.apps.safetyhub
adb shell cmd package install-existing com.google.android.apps.searchlite
adb shell cmd package install-existing com.google.android.apps.security.securityhub
adb shell cmd package install-existing com.google.android.apps.seekh
adb shell cmd package install-existing com.google.android.apps.subscriptions.red
adb shell cmd package install-existing com.google.android.apps.tachyon
adb shell cmd package install-existing com.google.android.apps.tasks
adb shell cmd package install-existing com.google.android.apps.translate
adb shell cmd package install-existing com.google.android.apps.turbo
adb shell cmd package install-existing com.google.android.apps.tycho
adb shell cmd package install-existing com.google.android.apps.userpanel
adb shell cmd package install-existing com.google.android.apps.village.boond
adb shell cmd package install-existing com.google.android.apps.walletnfcrel
adb shell cmd package install-existing com.google.android.apps.wallpaper
adb shell cmd package install-existing com.google.android.apps.wear.companion
adb shell cmd package install-existing com.google.android.apps.wearables.maestro.companion
adb shell cmd package install-existing com.google.android.apps.wellbeing
adb shell cmd package install-existing com.google.android.apps.wifisetup.app
adb shell cmd package install-existing com.google.android.apps.work.clouddpc
adb shell cmd package install-existing com.google.android.apps.youtube.creator
adb shell cmd package install-existing com.google.android.apps.youtube.kids
adb shell cmd package install-existing com.google.android.apps.youtube.music
adb shell cmd package install-existing com.google.android.apps.youtube.music.pwa
adb shell cmd package install-existing com.google.android.apps.youtube.producer
adb shell cmd package install-existing com.google.android.apps.youtube.unplugged
adb shell cmd package install-existing com.google.android.as
adb shell cmd package install-existing com.google.android.as.oss
adb shell cmd package install-existing com.google.android.backdrop
adb shell cmd package install-existing com.google.android.backuptransport
adb shell cmd package install-existing com.google.android.calculator
adb shell cmd package install-existing com.google.android.calendar
adb shell cmd package install-existing com.google.android.cellbroadcastreceiver
adb shell cmd package install-existing com.google.android.cellbroadcastservice
adb shell cmd package install-existing com.google.android.configupdater
adb shell cmd package install-existing com.google.android.connectivity.resources
adb shell cmd package install-existing com.google.android.contacts
adb shell cmd package install-existing com.google.android.deskclock
adb shell cmd package install-existing com.google.android.dialer
adb shell cmd package install-existing com.google.android.documentsui
adb shell cmd package install-existing com.google.android.embedded.projection
adb shell cmd package install-existing com.google.android.euicc
adb shell cmd package install-existing com.google.android.ext.shared
adb shell cmd package install-existing com.google.android.feedback
adb shell cmd package install-existing com.google.android.gm
adb shell cmd package install-existing com.google.android.gm.lite
adb shell cmd package install-existing com.google.android.gms
adb shell cmd package install-existing com.google.android.gms.location.history
adb shell cmd package install-existing com.google.android.gms.supervision
adb shell cmd package install-existing com.google.android.GoogleCamera
adb shell cmd package install-existing com.google.android.googlequicksearchbox
adb shell cmd package install-existing com.google.android.gsf
adb shell cmd package install-existing com.google.android.gsf.login
adb shell cmd package install-existing com.google.android.ims
adb shell cmd package install-existing com.google.android.inputmethod.latin
adb shell cmd package install-existing com.google.android.instantapps.supervisor
adb shell cmd package install-existing com.google.android.katniss
adb shell cmd package install-existing com.google.android.keep
adb shell cmd package install-existing com.google.android.leanbacklauncher
adb shell cmd package install-existing com.google.android.marvin.talkback
adb shell cmd package install-existing com.google.android.music
adb shell cmd package install-existing com.google.android.nearby.halfsheet
adb shell cmd package install-existing com.google.android.networkstack.tethering
adb shell cmd package install-existing com.google.android.networkstack.tethering.overlay
adb shell cmd package install-existing com.google.android.ondevicepersonalization.services
adb shell cmd package install-existing com.google.android.onetimeinitializer
adb shell cmd package install-existing com.google.android.overlay.gmsconfig.asi
adb shell cmd package install-existing com.google.android.overlay.gmsconfig.common
adb shell cmd package install-existing com.google.android.overlay.gmsconfig.geotz
adb shell cmd package install-existing com.google.android.overlay.gmsconfig.gsa
adb shell cmd package install-existing com.google.android.overlay.gmsconfig.photos
adb shell cmd package install-existing com.google.android.overlay.modules.captiveportallogin.forframework
adb shell cmd package install-existing com.google.android.overlay.modules.cellbroadcastreceiver
adb shell cmd package install-existing com.google.android.overlay.modules.cellbroadcastservice
adb shell cmd package install-existing com.google.android.overlay.modules.documentsui
adb shell cmd package install-existing com.google.android.overlay.modules.ext.services
adb shell cmd package install-existing com.google.android.overlay.modules.modulemetadata.forframework
adb shell cmd package install-existing com.google.android.overlay.modules.permissioncontroller
adb shell cmd package install-existing com.google.android.overlay.modules.permissioncontroller.forframework
adb shell cmd package install-existing com.google.android.partnersetup
adb shell cmd package install-existing com.google.android.play.games
adb shell cmd package install-existing com.google.android.printservice.recommendation
adb shell cmd package install-existing com.google.android.projection.gearhead
adb shell cmd package install-existing com.google.android.providers.media.module
adb shell cmd package install-existing com.google.android.safetycenter.resources
adb shell cmd package install-existing com.google.android.sdksandbox
adb shell cmd package install-existing com.google.android.setupwizard
adb shell cmd package install-existing com.google.android.syncadapters.calendar
adb shell cmd package install-existing com.google.android.syncadapters.contacts
adb shell cmd package install-existing com.google.android.tts
adb shell cmd package install-existing com.google.android.tungsten.setupwraith
adb shell cmd package install-existing com.google.android.tv
adb shell cmd package install-existing com.google.android.tv.remote.service
adb shell cmd package install-existing com.google.android.tvlauncher
adb shell cmd package install-existing com.google.android.tvrecommendations
adb shell cmd package install-existing com.google.android.videos
adb shell cmd package install-existing com.google.android.wearable.app
adb shell cmd package install-existing com.google.android.wearable.assistant
adb shell cmd package install-existing com.google.android.wearable.fitbit.mcu.data
adb shell cmd package install-existing com.google.android.wearable.healthservices
adb shell cmd package install-existing com.google.android.wearable.pixel.pdms
adb shell cmd package install-existing com.google.android.wearable.protolayout.renderer
adb shell cmd package install-existing com.google.android.wearable.sysui
adb shell cmd package install-existing com.google.android.wearable.watchface.rwf
adb shell cmd package install-existing com.google.android.wearable.weather
adb shell cmd package install-existing com.google.android.webview
adb shell cmd package install-existing com.google.android.webview.beta
adb shell cmd package install-existing com.google.android.webview.canary
adb shell cmd package install-existing com.google.android.webview.dev
adb shell cmd package install-existing com.google.android.youtube
adb shell cmd package install-existing com.google.android.youtube.tv
adb shell cmd package install-existing com.google.android.youtube.tvkids
adb shell cmd package install-existing com.google.android.youtube.tvmusic
adb shell cmd package install-existing com.google.android.youtube.tvunplugged
adb shell cmd package install-existing com.google.ar.core
adb shell cmd package install-existing com.google.ar.lens
adb shell cmd package install-existing com.google.audio.hearing.visualization.accessibility.scribe
adb shell cmd package install-existing com.google.chromeremotedesktop
adb shell cmd package install-existing com.google.earth
adb shell cmd package install-existing com.google.enterprise.topaz.mobile.android
adb shell cmd package install-existing com.google.location.nearby.apps.fastpair.validator
adb shell cmd package install-existing com.google.research.projectrelate
adb shell cmd package install-existing com.google.samples.apps.cardboarddemo
adb shell cmd package install-existing com.google.samples.apps.iosched
adb shell cmd package install-existing com.google.socratic
adb shell cmd package install-existing com.google.toontastic
adb shell cmd package install-existing com.niksoftware.snapseed
